{
 "title": "Summary",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Workflow Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "temporal_workflow_endtoend_latency_seconds_sum{otel_scope_name=\"temporal\"}/temporal_workflow_endtoend_latency_seconds_count{otel_scope_name=\"temporal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Proxy Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(cache_usage_total{otel_scope_name=\"httpproxy\", type=\"hits\"}) / \nsum(cache_usage_total{otel_scope_name=\"httpproxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cache_size{otel_scope_name=\"httpproxy\", type=\"current\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cache_size{otel_scope_name=\"httpproxy\", type=\"max\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"agent\"}",
     "legendFormat": "{{job}}: heap reserved (avg)"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"agent\"}",
     "legendFormat": "{{job}}: heap in use (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"agent\"}",
     "legendFormat": "{{job}}: goroutine count (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0\", job=\"agent\"}",
     "legendFormat": "{{job}}: min gc time (avg)"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\", job=\"agent\"}",
     "legendFormat": "{{job}}: max gc time (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"agent\"} - go_memstats_frees_total{job=\"agent\"}",
     "legendFormat": "{{job}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"agent\"}[$__rate_interval])",
     "legendFormat": "{{job}}: obj mallocs/s (avg)"
    }
   ]
  }
 ]
}