apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true

- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  editable: true

- name: Tempo
  type: tempo
  url: http://tempo:3200
  access: proxy
  editable: true

- name: Parca
  type: parca
  url: http://parca:7070
  access: proxy
  editable: true
